In [ ]:
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import mean_squared_error

import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
pwd

'/content'

In [ ]:
cd drive/MyDrive/Colab_Notebooks/weather_bigdata_contest/data

/content/drive/MyDrive/Colab_Notebooks/weather_bigdata_contest/data


In [ ]:
X_train = pd.read_csv('../data/X_train_weather_columns_6.csv', encoding='CP949')
X_test = pd.read_csv('../data/X_test_weather_columns_6.csv', encoding='CP949')
y_train = pd.read_csv('../data/y_train_weather_columns_6.csv', encoding='CP949')
y_test = pd.read_csv('../data/y_test_weather_columns_6.csv', encoding='CP949')

# 판매량 회귀 예측

In [ ]:
del X_train['날짜']
del X_test['날짜']

In [ ]:
X_train.head()

소분류_가스온수기  소분류_가열식 가습기  소분류_감/홍시  ...  평균 상대습도(%)        O3       PM10
0          0            0         0  ...   33.037917  0.018290  48.410017
1          0            0         0  ...   73.183486  0.014360  51.295243
2          0            0         0  ...   43.799624  0.024148  69.525672
3          0            0         0  ...   62.992631  0.031252  20.653887
4          0            0         0  ...   44.816831  0.034980  42.917136

[5 rows x 135 columns]

In [ ]:
y_train

20대 남성 판매량(개)  20대 여성 판매량(개)  ...  60대 남성 선호도 점수  60대 여성 선호도 점수
0                0.0            1.0  ...       0.000000       0.284671
1                6.0           20.0  ...       0.097320       0.143339
2                0.0            0.0  ...       0.000000       0.000000
3                3.0            0.0  ...       0.367385       0.000000
4                7.0           88.0  ...       0.038242       0.122037
...              ...            ...  ...            ...            ...
56263            1.0            1.0  ...       0.000000       0.000000
56264            8.0           18.0  ...       0.172594       0.063552
56265            1.0            9.0  ...       0.000000       0.267868
56266            6.0           59.0  ...       0.045675       0.168184
56267           10.0           22.0  ...       0.173966       0.267876

[56268 rows x 22 columns]

In [ ]:
# 총판매량을 y데이터로 만들기
y_train = y_train['합계']
y_test = y_test['합계']

### 정규화 _ StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(X_train)

X_standard_train = ss.transform(X_train)
X_standard_test = ss.transform(X_test)

### Optimizer _ adam

In [ ]:
model_1 = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_1.compile(loss='mse',
              optimizer='adam')

In [ ]:
model_1.fit(X_standard_train, y_train, epochs=100)

Epoch 1/100
1759/1759 [==============================] - 3s 1ms/step - loss: 39395.1836
Epoch 2/100
1759/1759 [==============================] - 2s 1ms/step - loss: 19927.9727
Epoch 3/100
1759/1759 [==============================] - 2s 1ms/step - loss: 18363.0664
Epoch 4/100
1759/1759 [==============================] - 2s 1ms/step - loss: 17709.2832
Epoch 5/100
1759/1759 [==============================] - 2s 1ms/step - loss: 17353.3984
Epoch 6/100
1759/1759 [==============================] - 2s 1ms/step - loss: 17169.0898
Epoch 7/100
1759/1759 [==============================] - 2s 1ms/step - loss: 17022.8633
Epoch 8/100
1759/1759 [==============================] - 3s 1ms/step - loss: 16906.2148
Epoch 9/100
1759/1759 [==============================] - 2s 1ms/step - loss: 16783.1758
Epoch 10/100
1759/1759 [==============================] - 2s 1ms/step - loss: 16700.3418
Epoch 11/100
1759/1759 [==============================] - 3s 1ms/step - loss: 16646.2949
Epoch 12/100
1759/1759 [======

In [ ]:
predict_1 = model_1.predict(X_standard_test)

In [ ]:
mse = mean_squared_error(predict_1, y_test)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  17984.69122592514
RMSE :  134.10701408175913


# 선호도 점수 회귀 예측

In [ ]:
y_train = pd.read_csv('../data/y_train_weather_columns_6.csv', encoding='CP949')
y_test = pd.read_csv('../data/y_test_weather_columns_6.csv', encoding='CP949')

## 일별 물품 선호도 점수

In [ ]:
# 일별 물품 선호도 점수를 y데이터로 만들기
y_train_day_prefer = y_train['일별 물품 선호도 점수']
y_test_day_prefer = y_test['일별 물품 선호도 점수']

In [ ]:
y_train_day_prefer

0        0.000005
1        0.000037
2        0.000002
3        0.000005
4        0.000140
           ...   
56263    0.000002
56264    0.000041
56265    0.000020
56266    0.000039
56267    0.000226
Name: 일별 물품 선호도 점수, Length: 56268, dtype: float64

In [ ]:
model_day_prefer = keras.Sequential([
                   keras.layers.Dense(64, activation='relu', input_shape=[135]),
                   keras.layers.Dense(64, activation='relu'),
                   keras.layers.Dense(1)
])

model_day_prefer.compile(loss='mse', optimizer='adam')

model_day_prefer.fit(X_standard_train, y_train_day_prefer, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0148
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0011
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 4.5151e-04
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 3.2652e-04
Epoch 5/50
1759/1759 [==============================] - 2s 1ms/step - loss: 1.6764e-04
Epoch 6/50
1759/1759 [==============================] - 2s 1ms/step - loss: 3.9214e-05
Epoch 7/50
1759/1759 [==============================] - 2s 1ms/step - loss: 2.5488e-05
Epoch 8/50
1759/1759 [==============================] - 3s 1ms/step - loss: 5.7811e-06
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 3.2455e-06
Epoch 10/50
1759/1759 [==============================] - 2s 1ms/step - loss: 1.2842e-06
Epoch 11/50
1759/1759 [==============================] - 2s 1ms/step - loss: 2.0620e-07
Epoch 12/50
1759/1759 [==========================

In [ ]:
predict_day_prefer = model_day_prefer.predict(X_standard_test)

mse = mean_squared_error(predict_day_prefer, y_test_day_prefer)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  1.8451211147804793e-08
RMSE :  0.0001358352352955771


## 연령 성별별 선호도 점수 예측

In [ ]:
# 연령 성별별로 10개의 모델을 위한 y데이터 10개 만들기
y_train_20m = y_train['20대 남성 선호도 점수']
y_test_20m = y_test['20대 남성 선호도 점수']
y_train_20f = y_train['20대 여성 선호도 점수']
y_test_20f = y_test['20대 여성 선호도 점수']

y_train_30m = y_train['30대 남성 선호도 점수']
y_test_30m = y_test['30대 남성 선호도 점수']
y_train_30f = y_train['30대 여성 선호도 점수']
y_test_30f = y_test['30대 여성 선호도 점수']

y_train_40m = y_train['40대 남성 선호도 점수']
y_test_40m = y_test['40대 남성 선호도 점수']
y_train_40f = y_train['40대 여성 선호도 점수']
y_test_40f = y_test['40대 여성 선호도 점수']

y_train_50m = y_train['50대 남성 선호도 점수']
y_test_50m = y_test['50대 남성 선호도 점수']
y_train_50f = y_train['50대 여성 선호도 점수']
y_test_50f = y_test['50대 여성 선호도 점수']

y_train_60m = y_train['60대 남성 선호도 점수']
y_test_60m = y_test['60대 남성 선호도 점수']
y_train_60f = y_train['60대 여성 선호도 점수']
y_test_60f = y_test['60대 여성 선호도 점수']

### 20대 남성

In [ ]:
y_train_20m

0        0.000000
1        0.092382
2        0.000000
3        0.348746
4        0.028234
           ...   
56263    0.367905
56264    0.109225
56265    0.028774
56266    0.086716
56267    0.025021
Name: 20대 남성 선호도 점수, Length: 56268, dtype: float64

In [ ]:
model_20m = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_20m.compile(loss='mse', optimizer='adam')

model_20m.fit(X_standard_train, y_train_20m, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0198
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0117
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0111
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0100
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0097
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0096
Epoch 7/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0096
Epoch 8/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0096
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0096
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0095
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0095
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0095
E

In [ ]:
predict_20m = model_20m.predict(X_standard_test)

mse = mean_squared_error(predict_20m, y_test_20m)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.010575713616248313
RMSE :  0.1028382886684153


In [ ]:
predict_20m

array([[0.06266151],
       [0.09883453],
       [0.09400901],
       ...,
       [0.08344326],
       [0.0604971 ],
       [0.04961798]], dtype=float32)

### 20대 여성

In [ ]:
model_20f = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_20f.compile(loss='mse', optimizer='adam')

model_20f.fit(X_standard_train, y_train_20f, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0144
Epoch 2/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0092
Epoch 3/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0085
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0082
Epoch 5/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0080
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0080
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0080
Epoch 8/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0079
Epoch 9/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0079
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0079
Epoch 11/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0078
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0079
E

In [ ]:
predict_20f = model_20f.predict(X_standard_test)

mse = mean_squared_error(predict_20f, y_test_20f)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.008736307627544716
RMSE :  0.09346821720534053


### 30대 남성

In [ ]:
model_30m = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_30m.compile(loss='mse', optimizer='adam')

model_30m.fit(X_standard_train, y_train_30m, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0205
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0148
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0141
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0137
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0136
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0135
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0134
Epoch 8/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0134
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0134
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0133
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0133
Epoch 12/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0133
E

In [ ]:
predict_30m = model_30m.predict(X_standard_test)

mse = mean_squared_error(predict_30m, y_test_30m)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.01430601254168109
RMSE :  0.11960774448872903


### 30대 여성

In [ ]:
model_30f = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_30f.compile(loss='mse', optimizer='adam')

model_30f.fit(X_standard_train, y_train_30f, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0270
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0163
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0126
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0125
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0120
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0118
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0117
Epoch 8/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0117
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0116
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0116
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0116
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0116
E

In [ ]:
predict_30f = model_30f.predict(X_standard_test)

mse = mean_squared_error(predict_30f, y_test_30f)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

### 40대 남성

In [ ]:
model_40m = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_40m.compile(loss='mse', optimizer='adam')

model_40m.fit(X_standard_train, y_train_40m, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0258
Epoch 2/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0172
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0161
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0156
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0153
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0152
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0152
Epoch 8/50
1759/1759 [==============================] - 2s 1ms/step - loss: 0.0152
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0152
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0151
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0151
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0151
E

In [ ]:
predict_40m = model_40m.predict(X_standard_test)

mse = mean_squared_error(predict_40m, y_test_40m)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.01652334224939087
RMSE :  0.12854315325753787


### 40대 여성

In [ ]:
model_40f = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_40f.compile(loss='mse', optimizer='adam')

model_40f.fit(X_standard_train, y_train_40f, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0260
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0146
Epoch 3/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0133
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0126
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0122
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0120
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0119
Epoch 8/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0119
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0118
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0118
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0118
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0118
E

In [ ]:
predict_40f = model_40f.predict(X_standard_test)

mse = mean_squared_error(predict_40f, y_test_40f)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.012202516138275207
RMSE :  0.11046499960745579


### 50대 남성

In [ ]:
model_50m = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_50m.compile(loss='mse', optimizer='adam')

model_50m.fit(X_standard_train, y_train_50m, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0269
Epoch 2/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0168
Epoch 3/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0166
Epoch 4/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0158
Epoch 5/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0155
Epoch 6/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0154
Epoch 7/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0154
Epoch 8/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0154
Epoch 9/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0153
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0153
Epoch 11/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0153
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0152
E

In [ ]:
predict_50m = model_50m.predict(X_standard_test)

mse = mean_squared_error(predict_50m, y_test_50m)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.016594997759193732
RMSE :  0.12882157334543673


### 50대 여성

In [ ]:
model_50f = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_50f.compile(loss='mse', optimizer='adam')

model_50f.fit(X_standard_train, y_train_50f, epochs=50)

Epoch 1/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0198
Epoch 2/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0112
Epoch 3/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0107
Epoch 4/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0101
Epoch 5/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0099
Epoch 6/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0098
Epoch 7/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0098
Epoch 8/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0098
Epoch 9/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0098
Epoch 10/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0097
Epoch 11/50
1759/1759 [==============================] - 3s 2ms/step - loss: 0.0097
Epoch 12/50
1759/1759 [==============================] - 3s 1ms/step - loss: 0.0097
E

In [ ]:
predict_50f = model_50f.predict(X_standard_test)

mse = mean_squared_error(predict_50f, y_test_50f)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

### 60대 남성

In [ ]:
model_60m = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_60m.compile(loss='mse', optimizer='adam')

model_60m.fit(X_standard_train, y_train_60m, epochs=50)

In [ ]:
predict_60m = model_60m.predict(X_standard_test)

mse = mean_squared_error(predict_60m, y_test_60m)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.018332190368792904
RMSE :  0.13539641933519847


### 60대 여성

In [ ]:
model_60f = keras.Sequential([
              keras.layers.Dense(64, activation='relu', input_shape=[135]),
              keras.layers.Dense(64, activation='relu'),
              keras.layers.Dense(1)
])

model_60f.compile(loss='mse', optimizer='adam')

model_60f.fit(X_standard_train, y_train_60f, epochs=50)

In [ ]:
predict_60f = model_60f.predict(X_standard_test)

mse = mean_squared_error(predict_60f, y_test_60f)
print('MSE  : ', mse)
print('RMSE : ', np.sqrt(mse))

MSE  :  0.011774609684571046
RMSE :  0.10851087357758689


RMSE 0.9 ~ 0.135 정도

# 선호도 점수 분류 예측

In [ ]:
# 연령 성별별로 0 ~ 9의 정수를 주고 가장 선호도 점수가 높은 클래스를 뽑아 y 값으로 만들기  
def y_argmax(df):
    target = df.loc[:,'20대 남성 선호도 점수':'60대 여성 선호도 점수'].values.argmax(axis=1)
    return target

y_train_prefer = y_argmax(y_train)
y_test_prefer = y_argmax(y_test)

In [ ]:
y_train_prefer

array([9, 9, 5, ..., 9, 1, 9])

In [ ]:
# 60대가 좀 많다..
np.unique(y_train_prefer, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([6819, 5728, 5282, 3090, 4893, 2673, 6708, 4327, 9699, 7049]))

In [ ]:
np.unique(y_test_prefer, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2932, 2512, 2230, 1369, 2148, 1157, 2919, 1770, 4041, 3038]))

### standard _ adam

In [ ]:
model_prefer_class = keras.Sequential([
                     keras.layers.Dense(64, activation='relu', input_shape=[135]),
                     keras.layers.Dense(64, activation='relu'),
                     keras.layers.Dense(10, activation='softmax')
])
model_prefer_class.compile(loss='sparse_categorical_crossentropy', 
                           optimizer='adam', metrics='accuracy')

In [ ]:
model_prefer_class.fit(X_standard_train, y_train_prefer, epochs=100)

Epoch 1/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.8666 - accuracy: 0.3159
Epoch 2/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7927 - accuracy: 0.3366
Epoch 3/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7806 - accuracy: 0.3389
Epoch 4/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7731 - accuracy: 0.3424
Epoch 5/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7675 - accuracy: 0.3433
Epoch 6/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7633 - accuracy: 0.3465
Epoch 7/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7594 - accuracy: 0.3474
Epoch 8/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7552 - accuracy: 0.3480
Epoch 9/100
1759/1759 [==============================] - 3s 2ms/step - loss: 1.7518 - accuracy: 0.3472
Epoch 10/100
1759/1759 [==============================] - 3s 2ms/step - l

In [ ]:
print("\n 테스트 정확도: %.4f" % (model_prefer_class.evaluate(X_standard_test, y_test_prefer)[1]))

754/754 [==============================] - 1s 1ms/step - loss: 1.8898 - accuracy: 0.3179

 테스트 정확도: 0.3179
